name: Remove old Docker image tags

on:
  workflow_dispatch:
    inputs:
      numberOfImagesToKeep:
        description: "Number of images to keep"
        required: true
        default: "5"


jobs:
  delete-image-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Delete old Docker images
        uses: m3ntorship/action-dockerhub-cleanup@1.4
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          keep-last: ${{ github.event.inputs.numberOfImagesToKeep }}
          repos: noxone/regexgenerator

