name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 2 * * *" # daily at 02:00
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2